springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # This tells the browser: "Ask the BFF for the menu list here"
    config-url: /v2/api-docs/swagger-config
    urls:
      - name: "Tejraj QHSE"
        url: /tejraj/v2/api-docs
      - name: "Ashwinsheth QHSE"
        url: /ashwinsheth/v2/api-docs
      - name: "GEM QHSE"
        url: /gemqhse/v2/api-docs
app-routes:
  routes:
    tejraj: "8081"
    ashwinsheth: "8082"
    gemqhse: "8083"