springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # This tells the browser: "Ask the BFF for the menu list here"
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: "Tejraj QHSE"
        url: /tejraj/v3/api-docs
      - name: "Ashwinsheth QHSE"
        url: /ashwinsheth/v3/api-docs
      - name: "GEM QHSE"
        url: /gemqhsebe/v3/api-docs
      - name: "Indospace Admin"
        url: /indospaceadmin/v3/api-docs
      - name: "Raymond Safety Admin"
        url: /raymondsafetyadmin/v3/api-docs
      - name: "Ground Holding Safety Admin"
        url: /ghsafetyadmin/v3/api-docs
      - name: "Ground Holding QC Admin"
        url: /groundholdingqcadmin/v3/api-docs
      - name: "Tejraj Admin"
        url: /tejrajadmin/v3/api-docs
      - name: "Ashwin Sheth Admin"
        url: /ashwinshethadmin/v3/api-docs
      - name: "Gem Safety Admin"
        url: /gemsafetyadmin/v3/api-docs
      - name: "Gem QC Admin"
        url: /gemqcadmin/v3/api-docs
      - name: "Gem QC"
        url: /gemqc/v3/api-docs
      - name: "Raymond Safety"
        url: /raymondsafety/v3/api-docs
      - name: "Indospace Safety"
        url: /indospacesafety/v3/api-docs
      - name: "Ground Holding Safety"
        url: /groundholdingsafety/v3/api-docs
      - name: "Ground Holding QC"
        url: /groundholding/v3/api-docs
      - name: "Snagging"
        url: /snagging/v3/api-docs
      - name: "Structural Audit"
        url: /structuralaudit/v3/api-docs
      - name: "LVM"
        url: /lvm/v3/api-docs
      - name: "HCC Safety"
        url: /hccsafety/v3/api-docs
      - name: "Gem Safety"
        url: /gemsafety/v3/api-docs
      - name: "Hcc Admin"
        url: /hccadmin/v3/api-docs
      - name: "Ashray QHSE"
        url: /ashray/v3/api-docs
      - name: "Ashray Admin"
        url: /ashrayadmin/v3/api-docs
      - name: "Gem QHSE Admin"
        url: /gemqhseadmin/v3/api-docs
      - name: "Notandas QHSE"
        url: /notandas/v3/api-docs
      - name: "Holystico QHSE"
        url: /holystico/v3/api-docs
app-routes:
  routes:
    tejraj: "8081"
    ashwinsheth: "8082"
    gemqhsebe: "8083"
    indospaceadmin: "8084"
    raymondsafetyadmin: "8085"
    ghsafetyadmin: "8086"
    groundholdingqcadmin: "8087"
    tejrajadmin: "8088"
    ashwinshethadmin: "8089"
    gemsafetyadmin: "8090"
    gemadmin: "8091"
    gemqc: "8092"
    raymondsafety: "8093"
    indospacesafety: "8094"
    groundholdingsafety: "8095"
    groundholding: "8096"
    snagging: "8097"
    structuralaudit: "8098"
    lvm: "8099"
    hccsafety: "8100"
    gemsafety: "8101"
    hccadmin: "8102"
    ashray: "8103"
    ashrayadmin: "8104"
    gemqhseadmin: "8105"
    notandas: "8106"
    holystico: "8107"

app:
  cors:
    allowed-origins: "http://13.232.224.37:8080,http://localhost:4200,http://192.168.1.4:4200"